/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a ../src/vpublishingservice_interface.h: ./vpubservice.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VPUBLISHINGSERVICE_INTERFACE_H_1395574950
#define VPUBLISHINGSERVICE_INTERFACE_H_1395574950

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface vpub.daemon.dbus.service
 */
class ServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "vpub.daemon.dbus.service")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"vpub.daemon.dbus.service\">\n"
"    <signal name=\"status\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"timestamp\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ServiceAdaptor(QObject *parent);
    virtual ~ServiceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void status(const QString &timestamp);
};

#endif
